# Site settings
title: Matteo Barbieri
email: privacy.mttbrbr@gmail.com
description: >-
  MSc student in Aeronautical Engineering @ Politecnico di Milano. 
  Focusing on aerodynamics, CFD, and control systems.
baseurl: "" 
url: "https://mttbrbr.github.io" # Fondamentale per GitHub Pages

# Social
github_username: mttbrbr

# Build settings
# Rimosso remote_theme e theme per usare i tuoi layout personalizzati
timezone: Europe/Rome

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default" # Usiamo default per semplicità, o "post" se ne crei uno specifico
  - scope:
      path: "_projects"
      type: "projects"
    values:
      layout: "default"

# SEO & Language
author: Matteo Barbieri
lang: en

# Exclude
exclude:
  - vendor/
  - .bundle/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock

highlighter: rouge
markdown: kramdown
